"""Language v3: subword tokenisation, sequence decoding, document distance,
discriminative tagging, and generation metrics.

Five more language tools. The unigram tokenizer learns a subword vocabulary by EM.
Beam search decodes a high-probability sequence without enumerating all of them.
Word Mover's Distance measures document similarity by optimal transport over word
embeddings. The averaged-perceptron tagger is a fast discriminative sequence
labeller. BLEU and ROUGE score generated text against references.
"""
import re
from collections import defaultdict, Counter

import numpy as np


_WORD = re.compile(r"[A-Za-z']+")


def _tokenize(text):
    return _WORD.findall(text.lower())


class UnigramTokenizer:
    """Learn a subword vocabulary by EM over a lattice (Kudo, 2018).

    BPE grows a vocabulary greedily by merging frequent pairs. The unigram model
    (SentencePiece's other algorithm) works TOP-DOWN and probabilistically: start
    from a large pool of candidate pieces, treat each word as generated by an
    unordered choice of pieces, and use EM to fit their probabilities -- the E-step
    finds each word's best segmentation, the M-step re-estimates piece
    probabilities -- then PRUNE the least useful pieces and repeat until the target
    size. The result is a probabilistic tokenizer that can score alternative
    segmentations, not just produce one. Hard-EM (Viterbi) variant here.
    """

    def __init__(self, vocab_size=100, max_piece_len=6, n_iter=8, seed_size=400):
        self.vocab_size = vocab_size
        self.max_piece_len = max_piece_len
        self.n_iter = n_iter
        self.seed_size = seed_size

    def fit(self, corpus):
        words = Counter()
        for line in corpus:
            words.update(_tokenize(line))
        self.words_ = words
        # seed: all substrings up to max length, scored by frequency * length
        sub = Counter()
        chars = set()
        for w, c in words.items():
            for i in range(len(w)):
                chars.add(w[i])
                for j in range(i + 1, min(i + self.max_piece_len, len(w)) + 1):
                    sub[w[i:j]] += c
        seed = {p: s for p, s in sub.most_common(self.seed_size)}
        for ch in chars:                                 # single chars must stay
            seed.setdefault(ch, sub.get(ch, 1))
        total = sum(seed.values())
        logp = {p: np.log(s / total) for p, s in seed.items()}
        for _ in range(self.n_iter):
            counts = Counter()
            for w, c in words.items():
                for piece in self._viterbi(w, logp):
                    counts[piece] += c
            total = sum(counts.values())
            logp = {p: np.log(counts[p] / total)
                    for p in logp if counts[p] > 0}
            for ch in chars:                             # never drop a character
                logp.setdefault(ch, np.log(1e-6))
            if len(logp) > self.vocab_size:              # prune the least probable
                keep = sorted(logp, key=logp.get, reverse=True)
                keep = set(keep[:self.vocab_size]) | chars
                logp = {p: v for p, v in logp.items() if p in keep}
        self.logp_ = logp
        self.vocab_ = sorted(logp)
        return self

    def _viterbi(self, word, logp):
        n = len(word)
        best = [(-np.inf, None)] * (n + 1)
        best[0] = (0.0, None)
        for i in range(1, n + 1):
            for j in range(max(0, i - self.max_piece_len), i):
                piece = word[j:i]
                if piece in logp and best[j][0] + logp[piece] > best[i][0]:
                    best[i] = (best[j][0] + logp[piece], j)
        # backtrack
        pieces, i = [], n
        while i > 0:
            j = best[i][1]
            if j is None:                                # fall back to characters
                return list(word)
            pieces.append(word[j:i]); i = j
        return pieces[::-1]

    def encode(self, word):
        return self._viterbi(word.lower(), self.logp_)


def beam_search(score_fn, start, vocab, max_len, beam_width=3, eos=None):
    """Decode a high-probability sequence without a full search (classic).

    Greedy decoding commits to the single best token each step and cannot recover
    from an early mistake; exhaustive search is exponential. Beam search keeps the
    ``beam_width`` best partial sequences at every step, extends each by every token,
    scores them (``score_fn(sequence) -> log-prob of the next tokens``), and prunes
    back to the top ``beam_width`` -- a bounded-width breadth-first search that finds
    much better sequences than greedy for a small constant cost. ``score_fn(seq)``
    returns a vector of next-token log-probabilities over ``vocab``.
    """
    beams = [(0.0, list(start))]
    finished = []
    for _ in range(max_len):
        candidates = []
        for score, seq in beams:
            if eos is not None and seq and seq[-1] == eos:
                finished.append((score, seq)); continue
            logits = score_fn(seq)
            for tok, lp in zip(vocab, logits):
                candidates.append((score + lp, seq + [tok]))
        if not candidates:
            break
        candidates.sort(key=lambda x: x[0], reverse=True)
        beams = candidates[:beam_width]
    finished.extend(beams)
    return max(finished, key=lambda x: x[0])[1]


def word_movers_distance(doc1, doc2, embeddings, reg=0.0):
    """Document distance as optimal transport over word embeddings (Kusner, 2015).

    Two sentences can share no words yet mean the same thing. Word Mover's Distance
    measures how far the words of one document must "travel" in EMBEDDING space to
    match the other -- an optimal-transport problem where the ground cost is the
    euclidean distance between word vectors. It captures that "Obama speaks to the
    press" is close to "the president greets reporters" despite zero word overlap.
    ``embeddings`` maps a token to a vector (dict or callable); ``reg>0`` uses the
    faster entropic (Sinkhorn) approximation.
    """
    from scipy.spatial.distance import cdist
    from ..optimal_transport import sinkhorn

    def bow(doc):
        toks = [t for t in _tokenize(doc) if _get(embeddings, t) is not None]
        c = Counter(toks)
        words = list(c)
        weights = np.array([c[w] for w in words], float)
        return words, weights / weights.sum()

    w1, a = bow(doc1)
    w2, b = bow(doc2)
    if not w1 or not w2:
        return np.inf
    V1 = np.array([_get(embeddings, w) for w in w1])
    V2 = np.array([_get(embeddings, w) for w in w2])
    C = cdist(V1, V2)
    if reg > 0:
        plan, cost = sinkhorn(a, b, C, reg=reg)
        return float(cost)
    return float(_emd(a, b, C))


def _get(embeddings, token):
    if callable(embeddings):
        try:
            return np.asarray(embeddings(token), float)
        except Exception:
            return None
    return np.asarray(embeddings[token], float) if token in embeddings else None


def _emd(a, b, C):
    # exact earth mover's distance via a small transportation LP (greedy NW + ...)
    from scipy.optimize import linprog
    n, m = C.shape
    Aeq = np.zeros((n + m, n * m))
    for i in range(n):
        Aeq[i, i * m:(i + 1) * m] = 1
    for j in range(m):
        Aeq[n + j, j::m] = 1
    res = linprog(C.ravel(), A_eq=Aeq, b_eq=np.concatenate([a, b]),
                  bounds=[(0, None)] * (n * m), method="highs")
    return res.fun


class AveragedPerceptronTagger:
    """A fast discriminative sequence tagger with weight averaging (Collins, 2002).

    The structured perceptron tags a sequence, and on any mistake nudges the weights
    toward the gold features and away from the predicted ones -- no probabilities,
    just error-driven updates, which makes it very fast to train. Its one crucial
    trick is AVERAGING: the final weights are the average of every intermediate
    weight vector over training, which cancels the late-training thrashing a raw
    perceptron suffers and gives most of the benefit of a margin method for almost
    no cost. Features: current word, previous tag, suffixes.
    """

    def __init__(self, epochs=10, random_state=None):
        self.epochs = epochs
        self.random_state = random_state

    def _features(self, words, i, prev_tag):
        w = words[i]
        return [f"w={w}", f"prev={prev_tag}", f"suf={w[-3:]}", f"pre={w[:3]}",
                f"cap={w[0].isupper()}", "bias"]

    def fit(self, sentences, tag_seqs):
        self.tags_ = sorted({t for ts in tag_seqs for t in ts})
        weights = defaultdict(float)
        totals = defaultdict(float)
        rng = np.random.RandomState(self.random_state)
        c = 0
        order = list(range(len(sentences)))
        for _ in range(self.epochs):
            rng.shuffle(order)
            for si in order:
                words, gold = sentences[si], tag_seqs[si]
                prev = "START"
                for i in range(len(words)):
                    feats = self._features(words, i, prev)
                    pred = self._score(feats, weights)
                    if pred != gold[i]:
                        for f in feats:                  # perceptron update
                            weights[(f, gold[i])] += 1
                            weights[(f, pred)] -= 1
                    for f in feats:
                        totals[(f, gold[i])] += weights[(f, gold[i])]
                        totals[(f, pred)] += weights[(f, pred)]
                    c += 1
                    prev = gold[i]
        self.weights_ = {k: v / c for k, v in totals.items()}   # averaged weights
        return self

    def _score(self, feats, weights):
        best, best_s = self.tags_[0], -np.inf
        for t in self.tags_:
            s = sum(weights.get((f, t), 0.0) for f in feats)
            if s > best_s:
                best_s, best = s, t
        return best

    def predict(self, words):
        prev = "START"; out = []
        for i in range(len(words)):
            feats = self._features(words, i, prev)
            t = self._score(feats, self.weights_)
            out.append(t); prev = t
        return out


def _ngrams(tokens, n):
    return Counter(tuple(tokens[i:i + n]) for i in range(len(tokens) - n + 1))


def bleu(reference, candidate, max_n=4):
    """Modified n-gram PRECISION with a brevity penalty (Papineni, 2002).

    BLEU scores a machine translation against a reference by how many of its
    n-grams (for n=1..4) appear in the reference -- but CLIPPED, so repeating a
    correct word does not inflate the score -- combined as a geometric mean. A
    brevity penalty stops a system from gaming precision by emitting only a few
    high-confidence words. Precision-oriented; 1.0 is a perfect match.
    """
    ref, cand = _tokenize(reference), _tokenize(candidate)
    if not cand:
        return 0.0
    max_n = min(max_n, len(cand))                        # short sentences use fewer n
    precisions = []
    for n in range(1, max_n + 1):
        cand_ng = _ngrams(cand, n)
        ref_ng = _ngrams(ref, n)
        overlap = sum(min(c, ref_ng.get(g, 0)) for g, c in cand_ng.items())
        total = max(sum(cand_ng.values()), 1)
        precisions.append(overlap / total)
    if min(precisions) == 0:
        geo = 0.0
    else:
        geo = np.exp(np.mean([np.log(p) for p in precisions]))
    bp = 1.0 if len(cand) > len(ref) else np.exp(1 - len(ref) / max(len(cand), 1))
    return float(bp * geo)


def rouge_n(reference, candidate, n=1):
    """Recall-oriented n-gram overlap for summarisation (Lin, 2004)."""
    ref, cand = _tokenize(reference), _tokenize(candidate)
    ref_ng, cand_ng = _ngrams(ref, n), _ngrams(cand, n)
    overlap = sum(min(c, cand_ng.get(g, 0)) for g, c in ref_ng.items())
    return overlap / max(sum(ref_ng.values()), 1)        # recall


def rouge_l(reference, candidate, beta=1.2):
    """LCS-based F-measure -- rewards in-order overlap (Lin, 2004)."""
    ref, cand = _tokenize(reference), _tokenize(candidate)
    m, k = len(ref), len(cand)
    dp = np.zeros((m + 1, k + 1))
    for i in range(1, m + 1):
        for j in range(1, k + 1):
            dp[i, j] = dp[i - 1, j - 1] + 1 if ref[i - 1] == cand[j - 1] \
                else max(dp[i - 1, j], dp[i, j - 1])
    lcs = dp[m, k]
    if lcs == 0:
        return 0.0
    prec, rec = lcs / max(k, 1), lcs / max(m, 1)
    return float((1 + beta ** 2) * prec * rec / (rec + beta ** 2 * prec + 1e-12))


__all__ = ["UnigramTokenizer", "beam_search", "word_movers_distance",
           "AveragedPerceptronTagger", "bleu", "rouge_n", "rouge_l"]
