"""Learn a subword vocabulary by EM over a lattice (Kudo, 2018)."""
import re
from collections import defaultdict, Counter
import numpy as np


def _tokenize(text):
    return _WORD.findall(text.lower())


_WORD = re.compile(r"[A-Za-z']+")


class UnigramTokenizer:
    """Learn a subword vocabulary by EM over a lattice (Kudo, 2018).

    BPE grows a vocabulary greedily by merging frequent pairs. The unigram model
    (SentencePiece's other algorithm) works TOP-DOWN and probabilistically: start
    from a large pool of candidate pieces, treat each word as generated by an
    unordered choice of pieces, and use EM to fit their probabilities -- the E-step
    finds each word's best segmentation, the M-step re-estimates piece
    probabilities -- then PRUNE the least useful pieces and repeat until the target
    size. The result is a probabilistic tokenizer that can score alternative
    segmentations, not just produce one. Hard-EM (Viterbi) variant here.
    """

    def __init__(self, vocab_size=100, max_piece_len=6, n_iter=8, seed_size=400):
        self.vocab_size = vocab_size
        self.max_piece_len = max_piece_len
        self.n_iter = n_iter
        self.seed_size = seed_size

    def fit(self, corpus):
        words = Counter()
        for line in corpus:
            words.update(_tokenize(line))
        self.words_ = words
        # seed: all substrings up to max length, scored by frequency * length
        sub = Counter()
        chars = set()
        for w, c in words.items():
            for i in range(len(w)):
                chars.add(w[i])
                for j in range(i + 1, min(i + self.max_piece_len, len(w)) + 1):
                    sub[w[i:j]] += c
        seed = {p: s for p, s in sub.most_common(self.seed_size)}
        for ch in chars:                                 # single chars must stay
            seed.setdefault(ch, sub.get(ch, 1))
        total = sum(seed.values())
        logp = {p: np.log(s / total) for p, s in seed.items()}
        for _ in range(self.n_iter):
            counts = Counter()
            for w, c in words.items():
                for piece in self._viterbi(w, logp):
                    counts[piece] += c
            total = sum(counts.values())
            logp = {p: np.log(counts[p] / total)
                    for p in logp if counts[p] > 0}
            for ch in chars:                             # never drop a character
                logp.setdefault(ch, np.log(1e-6))
            if len(logp) > self.vocab_size:              # prune the least probable
                keep = sorted(logp, key=logp.get, reverse=True)
                keep = set(keep[:self.vocab_size]) | chars
                logp = {p: v for p, v in logp.items() if p in keep}
        self.logp_ = logp
        self.vocab_ = sorted(logp)
        return self

    def _viterbi(self, word, logp):
        n = len(word)
        best = [(-np.inf, None)] * (n + 1)
        best[0] = (0.0, None)
        for i in range(1, n + 1):
            for j in range(max(0, i - self.max_piece_len), i):
                piece = word[j:i]
                if piece in logp and best[j][0] + logp[piece] > best[i][0]:
                    best[i] = (best[j][0] + logp[piece], j)
        # backtrack
        pieces, i = [], n
        while i > 0:
            j = best[i][1]
            if j is None:                                # fall back to characters
                return list(word)
            pieces.append(word[j:i]); i = j
        return pieces[::-1]

    def encode(self, word):
        return self._viterbi(word.lower(), self.logp_)


__all__ = ["UnigramTokenizer"]
